
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.45.203:8501

2025-03-22 23:15:42.841 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\streamlit\dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert '-' with type str: tried to convert to int64", 'Conversion failed for column 인원 수 with type object')
건축비(공사비)를 입력해주세요
2025-03-22 23:30:21.658 Uncaught app execution
Traceback (most recent call last):
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\umts2\OneDrive\Desktop\ysg\main.py", line 37, in <module>
    df_house = Later_Assets_House(mem_union, avg_cost, avg_area, total_area)()
NameError: name 'Later_Assets_House' is not defined
2025-03-22 23:30:37.703 Uncaught app execution
Traceback (most recent call last):
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "C:\Users\umts2\anaconda3\envs\ysg\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\umts2\OneDrive\Desktop\ysg\main.py", line 52, in <module>
    st.dataframe(df_arcade)
  File "C:\Users\umts2\OneDrive\Desktop\ysg\web\web_Business_Cost.py", line 34, in __call__
    df_BudgetCost = budget_cal(selected_distrct, selected_BuildgingType, ConstCost, ConstArea)()
  File "C:\Users\umts2\OneDrive\Desktop\ysg\src_code\budget_cal.py", line 71, in __call__
    df = self.calculate_Budget_for_projects(data)
  File "C:\Users\umts2\OneDrive\Desktop\ysg\src_code\budget_cal.py", line 44, in calculate_Budget_for_projects
    self.construct_cost = int(input("건축비(공사비)를 입력해주세요\n"))
EOFError: EOF when reading a line
  Stopping...
